name: Deploy
on:
  release:
    types: [published]
jobs:
  release:
    name: Deploy to Maven
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“¦ Prepate Git Repo
        uses: actions/checkout@v2

      - name: ğŸ” Import GPG key
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: â˜• Install OpenJDK
        uses: AdoptOpenJDK/install-jdk@v1
        with:
          version: '11'
          architecture: x64

      - name: ğŸš€ Deploy to Maven
        run: mvn -B deploy -f pom.xml -s settings.xml
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

  build:
      name: Build
      runs-on: windows-2019
      steps:
        - name: ğŸ“¦ Prepate Git Repo
          uses: actions/checkout@v2

        - name: â˜• Install OpenJDK
          uses: AdoptOpenJDK/install-jdk@v1
          with:
            version: '11'
            architecture: x64

        - name: ğŸ“š Install jpackage
          uses: AdoptOpenJDK/install-jdk@v1
          with:
            version: '15'
            architecture: x64

        - name: ğŸ“¦ Build with Maven
          run: mvn -B package --file pom.xml

        - name: ğŸ“¦ Compile to exe
          run: sh ./build.sh

        - name: ğŸ“¦ Upload artifact
          uses: actions/upload-artifact@v2
          with:
            name: webdir
            path: webdir

        - name: ğŸš€ Deploy to Releases
          uses: AButler/upload-release-assets@v2.0
          with:
            files: 'webdir-api/target/*.jar'
            repo-token: ${{ secrets.GITHUB_TOKEN }}

    deploy:
      name: Deploy
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: ğŸ“¦ Download Artifact
          uses: actions/download-artifact@v2
          with:
            name: webdir
            path: webdir

        - name: ğŸ“¦ Zip file
          uses: papeloto/action-zip@v1
          with:
            files: webdir
            dest: webdir.zip

        - name: ğŸ’¾ Save to Releases
        uses: JasonEtco/upload-to-release@master
        with:
          args: webdir.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
